# Generated by Django 6.0.3 on 2026-04-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(max_length=200)),
                ('Amount', models.IntegerField()),
                ('Razorpay_Id', models.CharField(max_length=200)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
